variables:
  ml-ws-connection: 'IoTmodel' # Workspace Service Connection name
  ml-ws: 'IoT-Dev' # AML Workspace name
  ml-rg: 'MLOps-Dev-2' # AML resource Group name
  ml-ct: 'MLComputeCluster' # AML Compute cluster name
  ml-path: 'models' # Model directory path in repo
  ml-exp: 'IoT-exp' # Experiment name
  ml-model-name: 'IoT-model' # Model name
  ml-aks-name: 'IoT-model-dev' # AKS cluster name
  ml.computeVMSize: 'STANDARD_DS3_V2'
  ml.computeMaxNodes: '1'
  ml.computeMinNodes: '0'
  ml.computeIdleSecs: '300'

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.9'
  inputs:
    versionSpec: 3.9

- task: AzureCLI@2
  displayName: 'Install AML CLI'
  inputs:
    azureSubscription: $(ml-ws-connection)
    scriptLocation: inlineScript
    scriptType: 'bash'
    inlineScript: 'az extension add -n azure-cli-ml'

- task: AzureCLI@2
  displayName: 'Create/Use Workspace'
  inputs:
    azureSubscription: $(ml-ws-connection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: 'az ml workspace create -g $(ml-rg) -w $(ml-ws) --exist-ok --yes'

- task: AzureCLI@2
  displayName: 'Create/use compute'
  inputs:
    azureSubscription: $(ml-ws-connection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
     az ml computetarget create amlcompute -g $(ml-rg) -w $(ml-ws) -n $(ml-ct) -s $(ml.computeVMSize) --min-nodes $(ml.computeMinNodes) --max-nodes $(ml.computeMaxNodes) --idle-seconds-before-scaledown $(ml.computeIdleSecs) 
     

- bash: 'mkdir metadata && mkdir models'
  displayName: 'Bash Script'

- task: AzureCLI@2
  displayName: 'Train model'
  inputs:
    azureSubscription: $(ml-ws-connection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
     az ml run submit-script -g $(ml-rg) -w $(ml-ws) -e $(ml-exp) --ct $(ml-ct) -c IoTcompute --source-directory . --path environment -t ./metadata/run.json IOT.py --container_name IoTdata 
     

- task: AzureCLI@2
  displayName: 'Register model'
  inputs:
    azureSubscription: $(ml-ws-connection)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
     az ml model register -g $(ml-rg) -w $(ml-ws) -n $(ml-model-name) --asset-path outputs/iot_in_model.pkl --tag "model"="LogisticRegression"  --model-framework Custom -f ./metadata/run.json -t metadata/model.json
     

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
     **/metadata/*
     **/data/*
     **/environment/*
     **/Pipeline/*
     **/models/*
     **/outputs/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishPipelineArtifact@1
  displayName: 'Publish Pipeline Artifact'
  inputs:
    artifact: iot